[package]
name = "macros"
version = "0.0.1"
authors = ["tonis"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.19", features = ["nightly"] }
quote = "1.0.7"
syn = { version = "1.0.38", features = ["full"] }
node = { path = "../node" }